[project]
name = "headline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu>=1.13.0",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "sentence-transformers>=5.1.2",
    "tqdm>=4.67.1",
]
